// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(ShtoDBContext))]
    partial class ShtoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.DShto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("qyteti")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tabelat")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipiVetures")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("zona")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DShto");
                });
#pragma warning restore 612, 618
        }
    }
}
